main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "main"  # 複数のアプリを作る場合、url 名に名前空間を設定する
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.MyLoginView.as_view(), name="login"),
    path("my-tasks/", views.TaskListView.as_view(), name="my_tasks"),
    path("settings/", views.TemplateView.as_view(template_name="main/settings.html")),
    path(
        "username_change/", views.UsernameUpdateView.as_view(), name="username_change"
    ),
    path("email_change", views.EmailUpdateView.as_view(), name="email_change"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taskapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", include("main.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.conf import settings
from django.db import models


class Task(models.Model):
    """タスクモデル"""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="ユーザー", on_delete=models.CASCADE
    )
    title = models.CharField(verbose_name="タイトル", max_length=256)
    content = models.TextField(verbose_name="内容", blank=True, null=True)
    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    update_at = models.DateTimeField(verbose_name="更新日時", auto_now_add=True)
    # 後から付け足した項目のため null=True にする。締切を設けないタスクを許容するため blank=True にする。
    deadline = models.DateTimeField(verbose_name="締切日時", null=True, blank=True)
    is_completed = models.BooleanField(verbose_name="完了済", null=True, blank=True, default=False)

    class Meta:
        verbose_name_plural = "Task"

    def __str__(self) -> str:
        return self.title + ": " + self.content[:10]

main/forms.py
from django.utils import timezone

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import ModelForm, TextInput, Textarea, SplitDateTimeWidget

from .models import Task


class LoginForm(AuthenticationForm):
    pass


class SignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "password1",
            "password2",
        )


class TaskCreationForm(ModelForm):
    deadline = forms.SplitDateTimeField(
        label="締切日時",
        widget=forms.SplitDateTimeWidget(
            date_attrs={"type": "date"},
            time_attrs={"type": "time"},
        ),
        initial=timezone.now()
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Task
        fields = (
            "title",
            "content",
            "deadline",
        )
        widgets = {
            'title': TextInput(
                attrs={'class': 'new-task-form-control', 'id': 'new-task-title'}
            ),
            'content': Textarea(
                attrs={'class': 'new-task-form-control', 'id': 'new-task-content'}
            ),
            'deadline': SplitDateTimeWidget(
                attrs={'class': 'new-task-form-control', 'id': 'new-task-deadline'}
            ),
        }


class UsernameChangeForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ("username",)


class EmailChangeForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ("email",)

main/views.py
from typing import *
from django.utils import timezone
from datetime import timedelta, datetime
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import QuerySet, F, BooleanField, Case, When
from django.http import JsonResponse
from django.shortcuts import HttpResponse, redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    FormView,
    ListView,
    TemplateView,
    UpdateView,
)
from django.views.generic.edit import ModelFormMixin

from .forms import (
    EmailChangeForm,
    LoginForm,
    SignUpForm,
    TaskCreationForm,
    UsernameChangeForm,
)
from .models import Task

class IndexView(TemplateView):
    """インデックス画面を表示するためのビュー"""

    template_name = "main/index.html"


class SignUpView(CreateView):
    """会員登録用のビュー"""

    model = settings.AUTH_USER_MODEL
    form_class = SignUpForm
    success_url = reverse_lazy("main:my_tasks")
    template_name = "main/signup.html"


class MyLoginView(LoginView):
    """ログイン用のビュー"""

    template_name = "main/login.html"
    form_class = LoginForm


# インポートの順番に注意 (LoginRequiredMixin を先に書く必要がある)
class TaskListView(LoginRequiredMixin, ListView, ModelFormMixin):
    """自分のタスク一覧を取得するビュー"""

    model = Task
    context_object_name = "my_tasks_list"
    template_name = "main/my-tasks.html"

    def get_queryset(self) -> QuerySet[Any]:
        queryset = Task.objects.filter(user=self.request.user).annotate(
                remaining_datetime = F("deadline") - timezone.now(),
                is_deadline_passed=Case(
                    When(remaining_datetime__lt=timedelta(), then=True),
                    default=False,
                    output_field=BooleanField(),
                ),
            ).order_by("deadline")
        return queryset

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = {
            "username": self.request.user.username,
            "task_form": TaskCreationForm,
            "usernamechange_form": UsernameChangeForm(instance=self.request.user),
            "emailchange_form": EmailChangeForm(instance=self.request.user),
            "my_tasks_list": self.get_queryset(),
            "user": self.request.user,
        }
        return context

    def post(self, request):
        if not "name" in self.request.POST:
            form = TaskCreationForm(self.request.POST)
            print(form)
            if form.is_valid():
                form = form.save(commit=False)
                form.user = self.request.user
                form.save()
                return redirect("main:my_tasks")
            return redirect("main:my_tasks")

        elif "task-complete" in self.request.POST["name"]:
            complete_pk = int(self.request.POST.get("task-pk"))
            completed_task = Task.objects.get(pk=complete_pk)
            completed_task.is_completed = True
            completed_task.save()
            return JsonResponse({})
        
        elif "task-edit" in self.request.POST["name"]:
            # 編集できるようにする
            form_content = self.request.POST
            edit_pk = int(form_content.get("task-pk"))
            edit_task = Task.objects.get(pk=edit_pk)
            edit_task.title = form_content.get("title")
            edit_task.content = form_content.get("content")

            deadline_str = form_content.get("deadline_0") + " " + form_content.get("deadline_1")
            deadline_dt = timezone.make_aware(datetime.strptime(deadline_str, '%Y-%m-%d %H:%M'))
            edit_task.deadline = deadline_dt

            has_deadline, deadline_passed, deadline, remaining_datetime\
                 = self.deadline_preprocess(deadline_str)

            edit_task.save()
            return JsonResponse({
                "task-pk": form_content.get("task-pk"),
                "title": form_content.get("title"),
                "content": form_content.get("content"),
                "has_deadline": has_deadline,
                "deadline_passed": deadline_passed,
                "deadline": deadline,
                "remaining_datetime": remaining_datetime,
            })
        
    def deadline_preprocess(self, deadline_str: str):
        def elapsed_time(dt):
            has_deadline = True
            deadline_passed = False

            if not dt:
                has_deadline = False
                return has_deadline, None, None, None
            zero = timedelta()
            one_hour = timedelta(hours=1)
            one_day = timedelta(days=1)
            one_week = timedelta(days=7)
            two_weeks = timedelta(days=14)
            one_month = timedelta(days=30)

            if dt < zero:
                deadline_passed = True
                if -dt > one_day:
                    remaining_datetime = f"{-dt.days}日"
                elif -dt > one_hour:
                    remaining_datetime = f"{(-dt).seconds // 3600}時間{(-dt).seconds % 60}分"
                else:
                    remaining_datetime = f"{(-dt).seconds // 60}分"
            else:
                if dt < one_hour:  # 経過時間が 1 時間以内のとき
                    remaining_datetime = f"{dt.seconds // 60}分"
                elif dt < one_day:  # 経過時間が 1 日以内のとき
                    remaining_datetime = f"{dt.seconds // 3600}時間"
                elif dt < one_week:  # 経過時間が 1 週間以内のとき
                    remaining_datetime = f"{dt.days}日"
                elif dt < two_weeks:
                    remaining_datetime = f"1週間と{dt.days - 7}日"
                elif dt < one_month:
                    remaining_datetime = f"{dt.days}日"
                else:
                    remaining_datetime = f"{dt.days // 30}カ月と{dt.days % 30}日"
            return has_deadline, deadline_passed, remaining_datetime

        deadline_dt = timezone.make_aware(datetime.strptime(deadline_str, '%Y-%m-%d %H:%M'))
        # leading zero を消すために strftime を避ける
        deadline_str \
            = f"{deadline_dt.year}年{deadline_dt.month}月{deadline_dt.day}日{deadline_dt.hour}:{deadline_dt.minute}"
        has_deadline, deadline_passed, remaining_datetime = elapsed_time(deadline_dt - timezone.now())
        return \
            has_deadline, deadline_passed, deadline_str, remaining_datetime



class UsernameUpdateView(LoginRequiredMixin, UpdateView):
    """ユーザー名変更をしたときのビュー"""

    model = settings.AUTH_USER_MODEL
    template_name = "main/username_change.html"
    form_class = UsernameChangeForm
    success_url = "main:my_tasks"


class EmailUpdateView(LoginRequiredMixin, UpdateView):
    """Eメール変更をしたときのビュー"""

    model = settings.AUTH_USER_MODEL
    template_name = "main/email_change.html"
    success_url = "main:my_tasks"

main/templates/main/base.html
{% load static %}
{% load sass_tags %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0">
    {% block style %}{% endblock style %}
    <title>タスク管理</title>
</head>
<body>
    {% block header %}{% endblock header %}
    {% block content %}{% endblock content %}
    {% block footer %}{% endblock footer %}
    
    {% block script %}{% endblock script %}
        
</body>
</html>

main/templates/main/build_template.html
{% extends 'main/base.html' %}
{% load static %}
{% load sass_tags %} 

{% block style %}

{% endblock style %}

{% block header %}{% endblock header %}

{% block content %}

{% endblock content %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% load sass_tags %} 

{% block style %}

<link rel="stylesheet" href="{% sass_src 'main/scss/index.scss' %}">

{% endblock style %}

{% block header %}{% endblock header %}

{% block content %}

<a href="{% url 'main:login' %}">ログインへのリンク</a>
<a href="{% url 'main:signup' %}">新規登録へのリンク</a>

{% endblock content %}

main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}
{% load sass_tags %} 

{% block style %}

{% endblock style %}

{% block header %}{% endblock header %}

{% block content %}
<a href="{% url 'main:signup' %}">新規登録へ</a>
<form action="{% url 'main:login' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    
    {% for field in form %}
        {{ field }}
        {{ field.errors }}
    {% endfor %}
    
    <button type="submit">ログイン</button>
</form>

{% endblock content %}

main/templates/main/my-tasks.html
{% extends 'main/base.html' %}
{% load static task_app %}
{% load static %}
{% load sass_tags %} 

{% block style %}
<link rel="stylesheet" href="{% sass_src 'main/scss/my-tasks.scss' %}">
{% endblock style %}

{% block header %}{% endblock header %}

{% block content %}

<h2>{{ username }} のタスクリスト</h2>

<div>
    {% if user.icon %}
    <img src="{{ user.icon.url }}" alt="アイコン画像" class="task__icon">
    {% else %}
    <img src="{% static 'main/images/default-icon.png' %}" alt="デフォルトのアイコン画像" class="task__icon">
    {% endif %}
</div>

<img src="{% static 'main/images/settings.png' %}" alt="設定" id="settings-image" onclick="toggleVisibility('settings');">

<div id="settings" style="display: none;">
    <form method="post">
        {% csrf_token %}
        {{ usernamechange_form.as_p }}
        <input type="submit" value="完了">
    </form>
</div>

<h3>新しいタスク</h3>
<form action="{% url 'main:my_tasks' %}" method="post">
    {% csrf_token %}
    {{ task_form.non_field_errors }}
    <table id="new-task-table">
        <tr>
            <th id="new-task-title__header">{{ task_form.title.label_tag }}</th>
            <th id="new-task-content__header">{{ task_form.content.label_tag }}</th>
            <th id="new-task-deadline__header">{{ task_form.deadline.label_tag }}</th>
        </tr>
        <tr>
            <td>{{ task_form.title }}</td>
            <td>{{ task_form.content }}</td>
            <td>{{ task_form.deadline }}</td>
            <td><button type="submit">送信</button></td>
        </tr>
    </table>
</form>

<h3>タスク一覧</h3>
<div id="my-tasks">
    {% if not my_tasks_list %}
        <p id="task-notset">タスクはまだ設定されていません</p>
    {% else %}
        <p id="task-set">現在のタスク</p>
        <table id="task-table">
            <tr>
                <th class="task-table__header" id="task-title__header">タイトル</th>
                <th class="task-table__header" id="task-content__header">内容</th>
                <th class="task-table__header" id="task-deadline__header">締切日時</th>
                <th class="task-table__header" id="task-status__header">状態</th>
            </tr>
            {% for task in my_tasks_list %}
                {% if task.is_completed == False %}
                <tr id="task-{{ task.pk }}">
                    <td class="task-title">{{ task.title }}</td>
                    <td class="task-content">{{ task.content }}</td>

                    {% if task.deadline %}
                        <td class="task-deadline">{{ task.deadline }}</td>
                        {% if task.is_deadline_passed %}
                            <td class="task-remaining-datetime"><b>{{ task.remaining_datetime | deadline_passed_elapsed_time }}</b>過ぎています</td>
                        {% else %}
                            <td class="task-remaining-datetime">締切まで: {{ task.remaining_datetime | elapsed_time }}</td>
                        {% endif %}
                    {% else %}
                        <td class="task-no-deadline">締切なし</td>
                    {% endif %} {# task.deadline #}

                    <td class="task-complete-delete__container">
                        <form class="task-complete" action="" method="post">
                            {% csrf_token %}
                            <button type="submit" value="{{ task.pk }}" class="task-complete__btn">完了</button>
                        </form>
                    </td>
                    <td class="task-complete-edit__container">
                        <button type="submit" value="{{ task.pk }}" class="task-edit__btn" 
                        onclick="showElementAtPosition('task-edit__form-{{ task.id }}', event.clientX, event.clientY);">編集</button>
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </table>
        {% for task in my_tasks_list %}
            <form id="task-edit__form-{{ task.id }}" class="task-edit__form" action="" method="post", style="display: none;">
                {% csrf_token %}
                {{ task_form.non_field_errors }}
                <p class="task-edit__form__content">
                    タイトル: <input class="task-edit__form__content"  type="text" name="title" maxlength="256" required="" id="id_title" value="{{ task.title }}">
                </p>
                <p class="task-edit__form__content">
                    内容: <input class="task-edit__form__content" type="text" name="content" id="id_content" value="{{ task.content }}">
                </p>
                <p class="task-edit__form__content">
                    締切: <input class="task-edit__form__content" type="date" name="deadline_0" value="{{ task.deadline | extract_date_from_datetime }}" required="" id="id_deadline_0">
                <input type="time" name="deadline_1" value="{{ task.deadline | extract_time_from_datetime }}" required="" id="id_deadline_1">
                </p>
                <button  class="task-edit__form__content task-edit__submit-btn" type="submit" value="{{ task.pk }}">変更</button>
            </form>
        {% endfor %}
    {% endif %}    
</div>

{% endblock content %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'main/js/my-tasks-popup-settings.js' %}"></script>
<script type="module" src="{% static 'main/js/my-tasks-ajax.js' %}"></script>
{% endblock script %}

main/templates/main/settings.html
{% extends 'main/base.html' %}
{% load static %}
{% load sass_tags %} 

{% block style %}

{% endblock style %}

{% block header %}{% endblock header %}

{% block content %}
<a href="#">ユーザー名変更</a>
{% endblock content %}

main/templates/main/signup.html
{% extends 'main/base.html' %}
{% load static %}
{% load sass_tags %} 

{% block style %}

{% endblock style %}

{% block header %}{% endblock header %}

{% block content %}
<a href="{% url 'main:login' %}">ログインへ</a>
<form action="{% url 'main:signup' %}" method="post">
    {% csrf_token %}
    <label>ユーザーID</label>
    {{ form.username }}
    {{ form.username.errors }}
    <label>パスワード</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
    <label>パスワード(確認)</label>
    {{ form.password2 }}
    {{ form.password2.errors }}
    <button type = "submit">登録</button>
</form>

{% endblock content %}

main/templates/main/task-delete-confirm.html
削除しますか？